PUT  http://localhost:3000/UpdateBudget/60fd97b8f0a8cdae5bd86b0c
Content-Type: application/json

{
    "budget":2500
}
###
GET http://localhost:3000/expensesAll
###
GET http://localhost:3000/budgetAll
###
DELETE  http://localhost:3000/DeleteExpense/237415b8-5641-4cdc-97af-dsfsdf418a971062f88